### ISSUE TITLE
Cannot login via https

### ISSUE THREAD

**Issue by QuintinGiesbrecht** [Radiokot/photoprism-android-client#165] opened 2024-12-16 21:58 UTC
**What is wrong?**
Get an error logging in with self-signed certificate - cert is added to the device

**To Reproduce**
1. Go to connect to a library
2. enter details
3. add the certificate
4. tap connect
5. error: "library is not accessible: SSL HandshakeException: java.security.cert.CertPathValidatorException:Trust Anchor for certification path not found.

**Expected behavior**
should successfully add account (unless I am doing something wrong)

**Screenshots**

**Device (please complete the following information):**
 - Model: Google Pixel 8
 - Android version: 15

**Additional context**
I am new to PhotoPrism and this gallery app, but quite tech savvy (I work as an IT manager). I have self-signed my own cert, and then exported it, and added it to my computer, and my Android device. I can get to the website with no cert errors, but in this gallery app, it does not work.

Thanks!

**Comment by Radiokot** [comment] 2024-12-17 06:52
Hi.
The app can't establish a secure connection to your library because of SSL misconfiguration. There may not be a corresponding root certificate on the phone, or the server certificate chain may be incomplete, or you've specified the wrong port in the library root URL. 
  - Check if the library is accessible from a phone browser with the same URL, without security warnings
  - Follow [this checklist](https://github.com/Radiokot/photoprism-android-client/issues/130#issuecomment-1962339179) to check if you have created your cert and CA properly
  - The gallery doesn't work with PhotoPrism default TLS

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 15:31
I am using a lets encrypt cert now (assigned to the exact domain, not a wildcard), and I still get the same error. In my web browser on my device I can verify that the cert is signed by LE...any ideas??

Thanks!

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 17:33
OK, now I tried following your documentation on creating a self-signed cert. (https://gist.github.com/Radiokot/092dfa1bc480ae8209cb6f48dabe1904)

I can confirm that the correct info is in the right spots. 

I still get the same error. I exported the cert to a P12 format, imported on my phone as VPN and App, and then added that cert when configuring the gallery. I get the same error, so obviously I am doing something wrong, just not sure what it would be. Grateful for any pointers.

![pics-ssl](https://github.com/user-attachments/assets/18608692-2b82-45e9-99b6-28234864c68e)

**Comment by Radiokot** [comment] 2024-12-17 19:21
Your server configuration and all the certificate must be 100% correct in order for the app to connect.
Browser developers make an extra effort to make sites accessible even if they are slightly misconfigured, but there are no such workarounds in the gallery.

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 19:42
OK, then do I need to create my .p12 file to import on my phone from the fullchain.pem and the .key file?

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 20:09
I tried installing the ca.crt file, and it won't let me. My phone (a Google Pixel 8) says I can't use that file...Are there any step by step instructions for this? That would be very helpful. I have created LOTS of self signed and LE certs, and never run into this kind of fusiness before :)

Thanks!

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 20:17
Well, I got the CA cert to install...under CA (not VPN and Apps...duh, my mistake)...anyways, that installed. I also added my P12 file as well under VPN and Apps, and added that to the gallery app, and I still get the same error. I do have the fullchain.pem on my photoprism server....and it passes in a browser (although I realize that the gallery app is fussier)...is there any logging that would say what is causing the error so I can pin it down?

Thanks again!

**Comment by Radiokot** [comment] 2024-12-17 20:27
Sorry, I don't know what's the problem in your case. But every time someone reports SSL connection issues, it is always caused by misconfiguration and resolved by checking the configuration or re-configuring from scratch. If the error is related to the trust anchor, then it is either your phone doesn't trust the CA from the certificate, or the server doesn't return the full certification chain. There are no extra logs, unfortunately.

**Closed by Radiokot** 2024-12-17 20:27 UTC

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 20:28
OK, I will keep trying :) Thanks for the help.

Q

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 20:29
Oh, and just to clarify...I need the CA cert added to my phone as a CA so that it trusts what I am signing right? Once I have that, then I should be able to browse to my site on my phone with no cert errors right? Because I can't do that either...so that tells me something else is wrong on my end...

Also, for the app, if I want to connect via https, do I only need the CA cert added, or do I also need the P12 and add it on the phone, and then in the app?

Thanks again!

**Comment by QuintinGiesbrecht** [comment] 2024-12-17 20:32
Oh, and after resetting my browser, I can connect without errors in Chrome on my phone...so something else must be wrong with my cert...it would be nice to have some tool, or some logging to determine what about the cert that the gallery doesn't like...I will keep trying :)
